// ─── Filter Constants ───
// Checkout & Payment
export const FILTER_CHECKOUT_PRICE = 'FILTER_CHECKOUT_PRICE';
export const FILTER_PAYLINK_POST_DATA = 'FILTER_PAYLINK_POST_DATA';

// Navigation / Menu
export const FILTER_MENU_GROUPS = 'FILTER_MENU_GROUPS';

// Signup / Auth
export const FILTER_SIGNUP_DATA = 'FILTER_SIGNUP_DATA';
export const FILTER_AFTER_LOGIN_SHOULD_DO_REDIRECT = 'FILTER_AFTER_LOGIN_SHOULD_DO_REDIRECT';

// Subscription
export const FILTER_SUBSCRIPTION_PLAN_FREQUENCIES = 'FILTER_SUBSCRIPTION_PLAN_FREQUENCIES';

// Dashboard / List
export const FILTER_DASHBOARD_LIST_CREATE_BUTTON = 'FILTER_DASHBOARD_LIST_CREATE_BUTTON';
export const FILTER_DASHBOARD_LIST_SHOULD_RENDER_BULK_CREATE_BUTTON = 'FILTER_DASHBOARD_LIST_SHOULD_RENDER_BULK_CREATE_BUTTON';

// Website Builder
export const FILTER_WEBSITE_BUILDER_FULLSCREEN_TEXT_COLOR = 'FILTER_WEBSITE_BUILDER_FULLSCREEN_TEXT_COLOR';

// QR Code Form
export const FILTER_QRCODE_FORM_CHANGE_TYPE_BUTTON = 'FILTER_QRCODE_FORM_CHANGE_TYPE_BUTTON';
export const FILTER_QRCODE_FORM_SHOULD_RENDER_SAVE_AS_TEMPLATE_BUTTON = 'FILTER_QRCODE_FORM_SHOULD_RENDER_SAVE_AS_TEMPLATE_BUTTON';

// QR Code Row
export const FILTER_QRCODE_ROW_COPY = 'FILTER_QRCODE_ROW_COPY';
export const FILTER_QRCODE_ROW_ARCHIVE = 'FILTER_QRCODE_ROW_ARCHIVE';
export const FILTER_QRCODE_ROW_FOLDERS_LINK = 'FILTER_QRCODE_ROW_FOLDERS_LINK';
export const FILTER_QRCODE_ROW_SHOULD_DO_ACT_AS = 'FILTER_QRCODE_ROW_SHOULD_DO_ACT_AS';
export const FILTER_QRCODE_LINK_SHOULD_RENDER_SETTINGS_ICON = 'FILTER_QRCODE_LINK_SHOULD_RENDER_SETTINGS_ICON';

// QR Code Types
export const FILTER_QRCODE_TYPES = 'FILTER_QRCODE_TYPES';
export const FILTER_QRCODE_TYPES_CLASS_LIST = 'FILTER_QRCODE_TYPES_CLASS_LIST';

// Plugin Settings
export const FILTER_PLUGIN_SETTINGS_PAGE = 'FILTER_PLUGIN_SETTINGS_PAGE';

// ─── Action Constants ───
export const ACTION_CHECKOUT_ABOVE_PAYMENT_PROCESSORS_TAB = 'ACTION_CHECKOUT_ABOVE_PAYMENT_PROCESSORS_TAB';
export const ACTION_MY_ACCOUNT_BELOW_SUBSCRIPTION_MANAGEMENT = 'ACTION_MY_ACCOUNT_BELOW_SUBSCRIPTION_MANAGEMENT';
export const ACTION_LEAD_FORM_AFTER_STARS_QUESTION = 'ACTION_LEAD_FORM_AFTER_STARS_QUESTION';
export const ACTION_QRCODE_ROW_ACTIONS = 'ACTION_QRCODE_ROW_ACTIONS';
export const ACTION_QRCODE_LIST_PAGE_END = 'ACTION_QRCODE_LIST_PAGE_END';
