import { useState, useCallback } from 'react';
import { BlockEditorProps, LinkBlockContent } from '../types';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import {
  X,
  Link,
  ExternalLink,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Linkedin,
  Github,
  Globe,
  Mail,
  Phone,
  MessageSquare,
  MapPin,
  Calendar,
  Image,
  Video,
  Music,
  FileText,
  ShoppingCart,
  Book,
  Heart,
  Star,
  Zap,
  Coffee,
  DollarSign,
  Gift,
  Briefcase,
  Home,
  Info,
  Users,
  Settings,
  Shield,
  Lightbulb,
  Award,
  Bell,
  Camera,
  Cloud,
  Code,
  Compass,
  CreditCard,
  Database,
  Download,
  Edit,
  Feather,
  Filter,
  Flag,
  Folder,
  Frown,
  GiftIcon,
  HardDrive,
  Hash,
  Headphones,
  HelpCircle,
  Key,
  Laptop,
  Layers,
  Layout,
  LifeBuoy,
  Lock,
  LogOut,
  Maximize,
  Mic,
  Minimize,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Package,
  Paperclip,
  Pause,
  Percent,
  PieChart,
  Pin,
  Play,
  Pocket,
  Power,
  Printer,
  QrCode,
  RefreshCcw,
  Repeat,
  Save,
  Search,
  Send,
  Share2,
  Share,
  ShieldAlert,
  ShoppingCartIcon,
  Smile,
  Speaker,
  Square,
  Sun,
  Tablet,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  ToggleLeft,
  ToggleRight,
  Trash,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Type,
  Underline,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Verified,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wand2,
  Watch,
  Waves,
  Webhook,
  Wifi,
  Wind,
  Wrench,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

const LinkBlockIcons = {
  link: Link,
  externalLink: ExternalLink,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  github: Github,
  globe: Globe,
  mail: Mail,
  phone: Phone,
  messageSquare: MessageSquare,
  mapPin: MapPin,
  calendar: Calendar,
  image: Image,
  video: Video,
  music: Music,
  fileText: FileText,
  shoppingCart: ShoppingCart,
  book: Book,
  heart: Heart,
  star: Star,
  zap: Zap,
  coffee: Coffee,
  dollarSign: DollarSign,
  gift: Gift,
  briefcase: Briefcase,
  home: Home,
  info: Info,
  users: Users,
  settings: Settings,
  shield: Shield,
  lightbulb: Lightbulb,
  award: Award,
  bell: Bell,
  camera: Camera,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  creditCard: CreditCard,
  database: Database,
  download: Download,
  edit: Edit,
  feather: Feather,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  frown: Frown,
  giftIcon: GiftIcon,
  hardDrive: HardDrive,
  hash: Hash,
  headphones: Headphones,
  helpCircle: HelpCircle,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  layout: Layout,
  lifeBuoy: LifeBuoy,
  lock: Lock,
  logOut: LogOut,
  maximize: Maximize,
  mic: Mic,
  minimize: Minimize,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  mousePointer: MousePointer,
  move: Move,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  percent: Percent,
  pieChart: PieChart,
  pin: Pin,
  play: Play,
  pocket: Pocket,
  power: Power,
  printer: Printer,
  qrCode: QrCode,
  refreshCcw: RefreshCcw,
  repeat: Repeat,
  save: Save,
  search: Search,
  send: Send,
  share2: Share2,
  share: Share,
  shieldAlert: ShieldAlert,
  shoppingCartIcon: ShoppingCartIcon,
  smile: Smile,
  speaker: Speaker,
  square: Square,
  sun: Sun,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  ticket: Ticket,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trash: Trash,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  triangle: Triangle,
  truck: Truck,
  type: Type,
  underline: Underline,
  unlock: Unlock,
  upload: Upload,
  user: User,
  userCheck: UserCheck,
  userPlus: UserPlus,
  userX: UserX,
  verified: Verified,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  wallet: Wallet,
  wand2: Wand2,
  watch: Watch,
  waves: Waves,
  webhook: Webhook,
  wifi: Wifi,
  wind: Wind,
  wrench: Wrench,
  zapOff: ZapOff,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
};
